version: '3'

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password

  wordpress:
    image: programando/wordpress:latest
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    restart: always
    volumes:
        - "./wordpress:/var/www/html"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      VIRTUAL_HOST: programando-wp.de.docker,www.programando-wp.de.docker
      VIRTUAL_PORT: 8080
    extra_hosts:
      - laravel.docker:172.23.0.1

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_data:/etc/nginx

volumes:
    db_data:
    nginx_data:

networks:
  default:
    external:
      name: nginx-proxy