version: '3.7'
services:
  nginx:
    image: registry.gitlab.com/programando/wordpress:development
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.app-ui.entrypoints=websecure"
        - "traefik.http.services.app-ui.loadbalancer.server.port=4000"
        - "traefik.http.routers.app-ui.rule=Host(`qa.programando-wp.de`)"
        - "traefik.http.routers.app-ui.tls.certresolver=http"

networks:
    traefik-public:
        external: true